### ISSUE TITLE
Why is there no chapter 5

### ISSUE THREAD

**Issue by PhysicalElective2** [PacktPublishing/Learning-Neo4j-3x-Second-Editon#3]

**Comment by saurabhk710** [comment]
Hi @PhysicalElective2 the Chapter5 does not have a code. thats why theres no Chapter5

**Comment by wadael** [comment]
Hello,

I concur with Saurabh.
As you can read, there is very little commands/queries and they are rather short.

So I choose not to give them as code as I believe muscle memory must be trained too.

Good reading

Jérôme Bâton (author)
